Sources/StructuredQueriesCore/Documentation.docc/Articles/GettingStarted.md

The select closure specifies $0.title so the query will decode Strings

Fix in GettingStarted doc

---

Sources/StructuredQueriesCore/Operators.swift
Tests/StructuredQueriesTests/SQLMacroTests.swift
Tests/StructuredQueriesTests/UpdateTests.swift

This addresses an issue in which `==` resolves to the wrong standard library overload that compares optionals to `nil` literals.

Move == to any QueryExpression.

---

Sources/StructuredQueriesCore/Optional.swift
Tests/StructuredQueriesTests/SelectTests.swift

This makes it possible to use helpers that are defined on `SomeTable.TableColumns` when outer joining to the table.

Dynamic member lookup on optional table definitions

---

Sources/StructuredQueriesCore/PrimaryKeyed.swift
Sources/StructuredQueriesCore/TableColumn.swift

We should retain this info for folks that want to dynamically generate certain queries, like `CREATE TABLE` statements.

Hold onto a column's default value

---

Sources/StructuredQueriesCore/Statements/Select.swift
Tests/StructuredQueriesTests/SelectTests.swift

This adds the ability to have a conditional statement inside of a `having` clause.
```swift 
.having {
if includeConditional {
$0.id.count() > 3
}
}
```
I also added tests for `where` statements with conditionals.

added conditional having

---

Tests/StructuredQueriesTests/AggregateFunctionsTests.swift
Tests/StructuredQueriesTests/DeleteTests.swift
Tests/StructuredQueriesTests/InsertTests.swift
Tests/StructuredQueriesTests/JoinTests.swift
Tests/StructuredQueriesTests/LiveTests.swift
Tests/StructuredQueriesTests/PrimaryKeyedTableTests.swift
Tests/StructuredQueriesTests/SQLMacroTests.swift
Tests/StructuredQueriesTests/SelectTests.swift
Tests/StructuredQueriesTests/SelectionTests.swift
Tests/StructuredQueriesTests/Support/Schema.swift
Tests/StructuredQueriesTests/UnionTests.swift

We've got this strange inconsistency of using 'name' and 'title' for our test models, so let's just make it all 'title'.

Rename 'name' to 'title'.

---

Sources/StructuredQueriesCore/CaseExpression.swift
Tests/StructuredQueriesTests/CaseTests.swift

Fixes an ergonomic issue that otherwise required explicit `Optional.init`.

Add case expression overload for non-optional expressions

---

Sources/StructuredQueriesCore/Documentation.docc/Articles/InsertStatements.md
Sources/StructuredQueriesCore/SQLQueryExpression.swift
Sources/StructuredQueriesCore/Seeds.swift
Tests/StructuredQueriesTests/Support/Schema.swift

This type is mainly to simplify downstream integrations like `SharingGRDB`, which already provides such a tool defined directly on `GRDB.Database`. That tool will be able to simply use this tool, instead, and future integrations can also leverage it.

Add `Seeds` type for preparings seeds for a database

---

Sources/StructuredQueriesCore/QueryBindable.swift
Sources/StructuredQueriesCore/QueryDecodable.swift
Tests/StructuredQueriesTests/DecodingTests.swift

This commit makes it trivial to conform `LosslessStringConvertible` types to `QueryBindable`.

Synthesize `LosslessStringConvertible` `QueryBindable` conformances

---

Sources/StructuredQueriesCore/Documentation.docc/Articles/DefiningYourSchema.md
Sources/StructuredQueriesCore/Documentation.docc/Articles/QueryCookbook.md
Sources/StructuredQueriesCore/Documentation.docc/Extensions/QueryRepresentable.md
Sources/StructuredQueriesCore/Internal/Deprecations.swift
Sources/StructuredQueriesCore/QueryRepresentable/Codable+JSON.swift
Sources/StructuredQueriesCore/QueryRepresentable/Date+ISO8601.swift
Sources/StructuredQueriesCore/QueryRepresentable/Date+JulianDay.swift
Sources/StructuredQueriesCore/QueryRepresentable/Date+UnixTime.swift
Sources/StructuredQueriesCore/QueryRepresentable/UUID+Bytes.swift
Sources/StructuredQueriesCore/QueryRepresentable/UUID+Lowercased.swift
Sources/StructuredQueriesCore/QueryRepresentable/UUID+Uppercased.swift
Sources/StructuredQueriesCore/SQLite/JSONFunctions.swift
Tests/StructuredQueriesTests/DecodingTests.swift
Tests/StructuredQueriesTests/JSONFunctionsTests.swift
Tests/StructuredQueriesTests/KitchenSinkTests.swift
Tests/StructuredQueriesTests/SelectTests.swift

Currently, the various query representable wrappers must be used a very specific way when dealing with optionals, where the optional must be on the representation type, not the type being represented:
```swift
@Column(as: Date.ISO8601Representation?.self)  // ✅
var date: Date?
@Column(as: Date?.ISO8601Representation.self)  // ❌
var date: Date?
```
This PR adds a few helper type aliases to address this issue, so both now compile and do the right thing:
```swift
@Column(as: Date.ISO8601Representation?.self)  // ✅
var date: Date?
@Column(as: Date?.ISO8601Representation.self)  // ✅
var date: Date?
```
It also renames `JSONRepresentation` to `Codable.JSONRepresentation`, deprecating the former spelling. This also allows the optionality to be placed either place:
```swift
@Column(as: …
```

Improve query-representable UX

---

Sources/StructuredQueriesCore/SQLite/JSONFunctions.swift

Require `jsonGroupArray` take a query-bindable argument

---

Sources/StructuredQueriesCore/PrimaryKeyed.swift
Tests/StructuredQueriesTests/PrimaryKeyedTableTests.swift

Improves representable values like UUID:
```diff
-Reminder.find(UUID.LowercasedRepresentation(queryOutput: reminderID))
+Reminder.find(reminderID)
```

Find records through query output

---

Sources/StructuredQueriesCore/Documentation.docc/Articles/QueryCookbook.md

This PR fixes an issue where the link to the section “Pre-loading associations with JSON” in the QueryCookBook was broken due to a case mismatch.

Fix anchor link in QueryCookbook.md

---

Sources/StructuredQueriesCore/Documentation.docc/Articles/SafeSQLStrings.md

We should stress against using `SELECT *` and referring to table/column names using strings.

Add important note about safe SQL strings

---

Sources/StructuredQueries/Macros.swift
Sources/StructuredQueriesCore/QueryFragment.swift
Sources/StructuredQueriesCore/Statements/CommonTableExpression.swift
Sources/StructuredQueriesCore/Statements/Delete.swift
Sources/StructuredQueriesCore/Statements/Insert.swift
Sources/StructuredQueriesCore/Statements/Select.swift
Sources/StructuredQueriesCore/Statements/Update.swift
Sources/StructuredQueriesCore/Table.swift
Sources/StructuredQueriesMacros/TableMacro.swift
Sources/StructuredQueriesTestSupport/AssertQuery.swift
Tests/StructuredQueriesMacrosTests/TableMacroTests.swift
Tests/StructuredQueriesTests/SchemaTests.swift

This is useful when an app connects to multiple schemas that have overlapping table names.

Add support for explicit schema names

---

Sources/StructuredQueriesCore/Documentation.docc/Articles/SelectStatements.md
Sources/StructuredQueriesCore/Statements/Select.swift

Right now a `q.limit(1)` will strip the existing offset when it probably should't.
There are some wider, unknown implications with how the `LIMIT`/`OFFSET` clauses combine at the moment, and it'd be nice to codify in the future, but for now this at least fixes a potential bug.

Don't remove current offset when chaining limits

---

Sources/StructuredQueriesCore/TableAlias.swift
Tests/StructuredQueriesTests/SelectTests.swift

A question came up in Slack about `jsonGroupArray` not working when using table aliases. The problem was that `TableAlias` did not conditionally conform to `Codable`, but I went ahead and added a few more conditional conformances that might be handy.

Add some conditional conformances to TableAlias

---

Sources/StructuredQueriesCore/Statements/Select.swift
Tests/StructuredQueriesTests/CompileTimeTests.swift

We need to maintain overloads that overparenthesize the arguments passed to the `select` method to work around parameter pack bugs in Swift, but were missing one.

Add another `Select.select` overload

---

Sources/StructuredQueries/Macros.swift
Sources/StructuredQueriesCore/Statements/Select.swift
Sources/StructuredQueriesCore/Statements/Where.swift
Tests/StructuredQueriesTests/SelectTests.swift

This PR allows the following to work without qualifying the expression type:
```diff
Reminder.group {
-  #sql("date(\($0.dueDate))", as: Date?.self)
+  #sql("date(\($0.dueDate))")
}
```

Improve `group(by:)` ergonomics

---

Sources/StructuredQueriesCore/Documentation.docc/Extensions/QueryExpression.md
Sources/StructuredQueriesCore/Optional.swift
Tests/StructuredQueriesTests/SelectTests.swift

This PR adds helpers that make it a little easier to work with optional query expressions in a builder.
For example, if you want to execute a `LIKE` operator on an optional string, you currently have to resort to one of the following workarounds, that either muddy the underlying SQL or require escape hatches outside the type system:
```swift
.where { ($0.title ?? "").like("%foo%") }
// WHERE coalesce("title", '') LIKE '%foo%'
.where { #sql("\($0.title) LIKE '%foo%'") }
// WHERE "title" LIKE '%foo%'
```
This PR introduces `map` and `flatMap` operations on optional `QueryExpression`s that unwraps the expression, giving you additional flexibility in how you express your builder code:
```swift
.where { $0.title.map { $0.like("%foo%") } ?? false }
// WHERE coalesce("title" LIKE '%foo%', 0)
``` …

Add `QueryExpression<Optional>.map,flatMap`

---

Sources/StructuredQueriesCore/Internal/Deprecations.swift
Sources/StructuredQueriesCore/Internal/PrettyPrinting.swift
Sources/StructuredQueriesCore/QueryFragment.swift
Sources/StructuredQueriesCore/TableAlias.swift
Sources/StructuredQueriesSQLite/Database.swift

Currently, query fragments are modeled as strings with `?`s denoting bindings, and an array of bindings. Instead we should model things as a single array of segments that can be concatenated with whatever form of binding identifier we need. For example, Postgres can use `$1`, `$2`, etc.
This remodel also has the positive effect of safer debug descriptions for queries.

Begin to decouple query fragments from SQLite

---

Sources/StructuredQueriesCore/Operators.swift
Sources/StructuredQueriesCore/PrimaryKeyed.swift
Sources/StructuredQueriesCore/Statements/Select+DynamicMemberLookup.swift
Sources/StructuredQueriesCore/Statements/Where.swift
Sources/StructuredQueriesCore/TableDefinition.swift
Tests/StructuredQueriesTests/OperatorsTests.swift
Tests/StructuredQueriesTests/PrimaryKeyedTableTests.swift
Tests/StructuredQueriesTests/SelectTests.swift
Tests/StructuredQueriesTests/TableTests.swift

- Ability to call `Draft.find`
- Inheritance of the primary table's default scope
- Dynamic member lookup for table helpers

Draft Improvements

---

Sources/StructuredQueriesCore/AggregateFunctions.swift
Tests/StructuredQueriesTests/AggregateFunctionsTests.swift
Tests/StructuredQueriesTests/SelectTests.swift

Not sure if this breaks anything down the line, all tests passed for me and the output for min/max on date looked realistic. I did notice the snapshot changed to .low for priotity, but given that total works the same way on QueryValue it seemed to be a sensible change. 
Would note that either way the docs use date as an example for min(), which when optional Int tends to some odd results.
Noticed this when trying to use min aggregate on a date column

Generic min max

---

Sources/StructuredQueriesCore/Statements/Insert.swift
Tests/StructuredQueriesTests/InsertTests.swift

This allows you to insert from compound selects, values, and more.

Relax `INSERT`-`SELECT` to work with partial select statements

---

Sources/StructuredQueriesCore/QueryFragment.swift

```
@Table
struct Reminder {
let id: Int
var title = ""
var isCompleted = false
var priority: Int?
var dueDate: Date?
}
let query =  Reminder.where {$0.title == "Test" }
let (sql, bindings) = query.query.prepare{ "$\($0)" }
```
Before:
`SELECT "reminders"."id", "reminders"."title", "reminders"."isCompleted", "reminders"."priority", "reminders"."dueDate" FROM "reminders" WHERE ("reminders"."title" = $52)`
After:
`SELECT "reminders"."id", "reminders"."title", "reminders"."isCompleted", "reminders"."priority", "reminders"."dueDate" FROM "reminders" WHERE ("reminders"."title" = $1)`

Fix binding sequence number

---

Sources/StructuredQueriesCore/Internal/Deprecations.swift
Sources/StructuredQueriesCore/Statements/Insert.swift
Sources/StructuredQueriesCore/Updates.swift
Tests/StructuredQueriesTests/InsertTests.swift

Add `excluded` to upsert clauses

---

Tests/StructuredQueriesTests/InsertTests.swift

This test would have caught the regression introduced by #95.

Add test for upsert with representable

---

Sources/StructuredQueriesCore/Documentation.docc/Extensions/QueryExpression.md
Sources/StructuredQueriesCore/SQLite/JSONFunctions.swift
Tests/StructuredQueriesTests/JSONFunctionsTests.swift

Found use in a downstream project, so mainlining this.

Add `QueryExpression.jsonPatch`

---

Sources/StructuredQueriesCore/QueryFragment.swift

Another useful helper to incorporate back into the library.

Add query fragment interpolation helper for representable bindings

---

Sources/StructuredQueriesCore/Statements/Update.swift
Tests/StructuredQueriesTests/PrimaryKeyedTableTests.swift

Fixed `Row.update(row)` so that it doesn't refer to generated columns.

Generated column `UPDATE` fixes

---

Sources/StructuredQueriesCore/Documentation.docc/Extensions/PrimaryKeyedTable.md
Sources/StructuredQueriesCore/PrimaryKeyed.swift

It can be helpful to be able to pluck off a primary key for a row more simply when dealing with primary keyed tables in the abstract.

Add `PrimaryKeyedTable.primaryKey`

---

Sources/StructuredQueriesCore/Statements/Delete.swift
Sources/StructuredQueriesCore/Statements/Update.swift
Tests/StructuredQueriesTests/TableTests.swift

This was only being applied when the `where` came first.

Apply default scope to `Table.{delete,update}()`

---

Sources/StructuredQueriesCore/Statements/Where.swift
Tests/StructuredQueriesTests/WhereTests.swift

When called with a predicate-less `Where` it could lead to invalid SQL.

`Where.{and,or,not}()` fixes

---

Package.resolved
Sources/StructuredQueries/Macros.swift
Sources/StructuredQueriesCore/Documentation.docc/Extensions/Select.md
Sources/StructuredQueriesCore/Internal/Scope.swift
Sources/StructuredQueriesCore/Statements/CommonTableExpression.swift
Sources/StructuredQueriesCore/Statements/CompoundSelect.swift
Sources/StructuredQueriesCore/Statements/Delete.swift
Sources/StructuredQueriesCore/Statements/Select.swift
Sources/StructuredQueriesCore/Statements/Update.swift
Sources/StructuredQueriesCore/Statements/Where.swift
Sources/StructuredQueriesCore/Table.swift
Sources/StructuredQueriesMacros/TableMacro.swift
Tests/StructuredQueriesTests/CommonTableExpressionTests.swift
Tests/StructuredQueriesTests/DeleteTests.swift
Tests/StructuredQueriesTests/SelectTests.swift
Tests/StructuredQueriesTests/TableTests.swift
Tests/StructuredQueriesTests/UnionTests.swift
Tests/StructuredQueriesTests/UpdateTests.swift
Tests/StructuredQueriesTests/WhereTests.swift

Acts as a "black hole" query, rendering as an empty SQL string and not executed by the database.

Add `Table.none`

---

Sources/StructuredQueriesCore/QueryFragment.swift
Sources/StructuredQueriesMacros/SQLMacro.swift
Sources/StructuredQueriesMacros/TableMacro.swift

It's overly restrictive. While passing a query fragment directly is equivalent to `SQLQueryExpression(fragment)`, it doesn't seem worth a hard error.
Alternately we could make it a warning with a fix-it that swaps `#sql` for `SQLQueryExpression`, but not sure it's worth the distinction?

Remove `#sql` literal requirement

---

Sources/StructuredQueriesCore/Statements/Select.swift
Tests/StructuredQueriesTests/SelectTests.swift

Parameter packs break down when a pack generic is a single value (instead of a tuple) and has a conformance constraint. These overloads are to work around it.
Before 1.0 we should probably come up with a reasonable limitation of how joins work. Some ideas to reduce the overloads:
- Joins require no selected columns on either side. While it'd be nice to splat them, it just doesn't work well with parameter packs today.
- Joins require no joined tables on the righthand side. Again: it'd be nice to support this, but it doesn't work well in the language today.
This maybe even means joins take `Table.Type` instead of `Select<Table>`.
I think if these two limitations were known and documented we could eliminate the many of the overloads we've defined today.

Add join overloads for `Joins: Table`

---

Sources/StructuredQueriesCore/Triggers.swift
Tests/StructuredQueriesTests/TriggersTests.swift

Adds support for providing a customized expression that will be used when creating a temporary trigger.

Add datetime customization to createTemporaryTrigger

---

Sources/StructuredQueriesCore/Documentation.docc/Articles/MigrationGuides.md
Sources/StructuredQueriesCore/Documentation.docc/Articles/MigrationGuides/MigratingTo0.16.md
Sources/StructuredQueriesCore/Documentation.docc/StructuredQueriesCore.md
Sources/StructuredQueriesCore/Internal/Deprecations.swift
Sources/StructuredQueriesCore/QueryBindable+Foundation.swift
Sources/StructuredQueriesCore/QueryBindable.swift
Sources/StructuredQueriesCore/QueryRepresentable/Codable+JSON.swift
Sources/StructuredQueriesCore/QueryRepresentable/Date+JulianDay.swift
Sources/StructuredQueriesCore/QueryRepresentable/Date+UnixTime.swift
Sources/StructuredQueriesCore/QueryRepresentable/UUID+Bytes.swift
Sources/StructuredQueriesCore/QueryRepresentable/UUID+Uppercased.swift
Sources/StructuredQueriesCore/TableAlias.swift
Sources/StructuredQueriesSQLite/Macros.swift
Sources/StructuredQueriesSQLiteCore/DatabaseFunction.swift
Sources/StructuredQueriesSQLiteCore/Documentation.docc/Articles/CustomFunctions.md
Sources/StructuredQueriesSQLiteMacros/DatabaseFunctionMacro.swift
Tests/StructuredQueriesMacrosTests/DatabaseFunctionMacroTests.swift
Tests/StructuredQueriesTests/DatabaseFunctionTests.swift

This PR improves upon a few deficiencies of #151:
1. It forces the definition of `QueryBindable.init?(queryBinding:)`. This is a breaking change for folks that define their own types conforming to `QueryRepresentable, but we are in the 0.x stage still, and custom query representations should be relatively uncommon. Still, we have a new migration guide to help.
2. It introduces an `as:` parameter to `@DatabaseFunction` for defining functions that work with custom query representations, like JSON.

Database Functions Improvements

---

Sources/StructuredQueriesSQLite/Macros.swift
Sources/StructuredQueriesSQLiteMacros/DatabaseFunctionMacro.swift
Tests/StructuredQueriesMacrosTests/DatabaseFunctionMacroTests.swift
Tests/StructuredQueriesTests/DatabaseFunctionTests.swift

A `@DatabaseFunction` that is `Void`-returning will return `NULL` to SQLite.

Add support for `Void`-returning database functions

---

Package.resolved
Sources/StructuredQueriesCore/QueryBindable.swift
Sources/StructuredQueriesSQLiteCore/DatabaseFunction.swift
Sources/StructuredQueriesSQLiteMacros/DatabaseFunctionMacro.swift
Tests/StructuredQueriesMacrosTests/DatabaseFunctionMacroTests.swift
Tests/StructuredQueriesTests/DatabaseFunctionTests.swift

Nice find by @acosmicflamingo.

Functions should be generic over their query-representable types

---

Sources/StructuredQueriesSQLiteMacros/DatabaseFunctionMacro.swift
Tests/StructuredQueriesMacrosTests/DatabaseFunctionMacroTests.swift

Needed to trim the description to avoid incorporating trivia.

Fix for `@DatabaseFunction` when arguments are newline separated

---

Package.resolved
Sources/StructuredQueriesSQLiteCore/FTS5.swift
Tests/StructuredQueriesTests/FTSTests.swift

Currently the helpers are only surfaced directly on a conformance. This commit extends the availability to optional tables and table aliases via conditional conformance.

FTS5: Support outer joins and aliased tables

---

Sources/StructuredQueriesSQLiteCore/Documentation.docc/Articles/Views.md
Sources/StructuredQueriesSQLiteCore/Documentation.docc/StructuredQueriesSQLiteCore.md
Sources/StructuredQueriesSQLiteCore/Views.swift
Tests/StructuredQueriesTests/ViewsTests.swift

Like temporary triggers
(https://github.com/pointfreeco/swift-structured-queries/pull/82), temporary views can be created in a completely type-safe manner due to their transitive nature.

Add type-safe API for creating temporary views

---

Package.resolved
Sources/StructuredQueriesCore/Statements/CommonTableExpression.swift
Sources/StructuredQueriesSQLiteCore/Views.swift
Tests/StructuredQueriesTests/ViewsTests.swift

A common use case for views is more complex common table expressions.

Add CTE support to `createTemporaryView`

---

Sources/StructuredQueriesMacros/SelectionMacro.swift
Sources/StructuredQueriesSQLiteCore/Documentation.docc/Articles/Triggers.md
Tests/StructuredQueriesMacrosTests/SelectionMacroTests.swift

Quick thing we noticed when working on an app.

Support defaults in `@Selection.Columns.init`

---

Sources/StructuredQueriesCore/PrimaryKeyed.swift
Tests/StructuredQueriesTests/PrimaryKeyedTableTests.swift
Tests/StructuredQueriesTests/UpdateTests.swift
Tests/StructuredQueriesTests/WhereTests.swift

We currently allow `Table.find(/*SELECT …*/)` but it will actually only find a single row, not all rows matching. So I've updated all of these types of queries to be "IN" instead of "=".
An alternative is to provide all new APIs for `findAll` if we want to distinguish between finding a single row versus finding many, but I'm not sure if there's a lot of benefit to that. It seems like it can be inferred from the argument provided to `find`.
Also I wonder if we should support `Table.find([1, 2, 3])`.

Support finding multiple rows by primary key.

---

Package@swift-6.0.swift
Tests/StructuredQueriesTests/ViewsTests.swift

We had a merge issue bring in a duplicate target in the Package.swift file.

Fix warning on Swift 6.0

---

Tests/StructuredQueriesTests/TriggerDefaultNameTests.swift
Tests/StructuredQueriesTests/TriggersTests.swift

Let's not use the default file/line-based names.

Infrastructure: reduce churn in trigger tests

---

Package.swift
Sources/StructuredQueriesMacros/TableMacro.swift
Tests/StructuredQueriesMacrosTests/TableMacroTests.swift

In #108 we accidentally broke macro generated code when using default main actor isolation. This fixes things.

Fix default main actor isolation.
